- roles/local_ci/local_ci_run/templates/pod.yaml.j2
- testing/codeflare/command_args.yml.j2
- testing/codeflare/prepare_user_pods.py
- testing/common/prepare_user_pods.py
- testing/pipelines/command_args.yml.j2
- testing/pipelines/test.py
- testing/watsonx-serving/command_args.yml.j2
so that we get the merged commit, not the branch `HEAD`. This could lead to failures when the PR is not rebased.
> Update PR references from /head to /merge

- testing/common/run.py
gets a permission denied error, because pid 1 is already group leader
> testing: common: run: do not call os.setpgrp on PID 1

- testing/watsonx-serving/config.yaml
- visualizations/watsonx-serving-scale/plotting/prom_report.py
- visualizations/watsonx-serving-scale/store/prom.py
```
e2e_perf_flan:
extends: [e2e_perf]
tests.e2e.llm_load_test.duration: 10m
watsonx_serving.model.serving_runtime.mute_logs: false # secret key has been disabled
tests.e2e.models:
- flan-t5-small-gpu-2gb:
name: flan-t5-small-gpu
serving_runtime:
resource_request:
memory: 2 # in Gi
- flan-t5-small-gpu-3gb:
name: flan-t5-small-gpu
serving_runtime:
resource_request:
memory: 3 # in Gi
- flan-t5-small-gpu-4gb:
name: flan-t5-small-gpu
serving_runtime:
resource_request:
memory: 4 # in Gi
- flan-t5-small-gpu-5gb:
name: flan-t5-small-gpu
serving_runtime:
resource_request:
memory: 5 # in Gi
```
```
e2e_perf_mbt:
extends: [e2e_perf_strict_limits]
tests.e2e.llm_load_test.duration: 1m
tests.e2e.models:
- mpt-7b-instruct2-8gb:
name: mpt-7b-instruct2
serving_runtime:
resource_request:
memory: 8 # in Gi …
```
> Watsonx: test mbt & flan memory profiles

- config/ansible.cfg
- topsail/_common.py
This commit allows to dinamically include
all the roles in the repository so the Ansible
interpreter can find them independently of
how many roles are in the repository.
> Remove hardwired roles inclusion

- roles/rhods/rhods_update_datasciencecluster/tasks/main.yml
`oc replace` can fail with:
```
<stderr>
Error from server (Conflict): error when replacing
"/logs/artifacts/013__sutest_rhods__update_datasciencecluster/src/datascience_cluster.yaml":
Operation cannot be fulfilled on
datascienceclusters.datasciencecluster.opendatahub.io "default-dsc":
the object has been modified; please apply your changes to the latest
version and try again
```
> rhods_update_datasciencecluster: use `oc delete/create` instead of `oc replace`

- .gitleaks.toml
- README.rst
- build/Dockerfile
- docs/conf.py
- docs/index.rst
- testing/run
I found a few places where ci-artifacts should be replaced with topsail, that should have no impact on functionality.
> Minor ci-artifacts -> topsail rename cleanup

- projects/kserve/testing/config.yaml
This reverts commit e9ac94dda72eb4fa518587ad88e1071ab316fd75.
Merged by mistake
> Revert "[kserve] testing: config: update to RHOAI 2.6-pre-rc"

- projects/notebooks/roles/notebooks_ods_ci_scale_test/files/ods-ci/notebook_dsg_test.robot
Fix for some of the XPaths used to work with workbenches in the DS projects page.
Feel free to test before you merge, I'm not fully sure how :slightly_smiling_face:
> [notebooks] updates XPaths for RHOAI 2.7

- projects/kserve/testing/config.yaml
- projects/kserve/testing/test_scale.py
As discussed on slack, I believe these changes should enable us to use the internal minio S3 service to pull the model files when running the kserve tests in the VPN.
> [kserve] Add option to use internal minio for model files

- projects/kserve/roles/kserve_deploy_model/tasks/main.yml
next task should fail anyway
OOM appears in the initContainer. Might not be fatal
> [kserve] roles: kserve_deploy_model: do not fail if the model initContainer fails

- projects/kserve/testing/config.yaml
without that, the test config relies on the default values ...
> [kserve] testing: config: extend the e2e_perf preset in watsonx_single_model_gating

- testing/utils/openshift_ci/pr_args.sh
Basically this lets new members of the repo who has not made any contributions before to run prow CI jobs. Here is the break down of individual commands just to make sure the data that is being returned is in the desired shape.
```
[cmusali@cmusali topsail]$ cat issue_comments.json | jq '.[] 
> | select(.author_association == "'${REQUIRED_AUTHOR_ASSOCIATION[0]}'", .author_association == "'${REQUIRED_AUTHOR_ASSOCIATION[1]}'")
>                              | .body'
"/test rhoai-light kserve quick_raw"
"/test rhoai-light kserve quick_raw\r\n\r\n"
"/test rhoai-light kserve quick_raw"
[cmusali@cmusali topsail]$ REQUIRED_AUTHOR_ASSOCIATION=("CONTRIBUTOR")
[cmusali@cmusali topsail]$ cat issue_comments.json | jq '.[] 
| select(.author_association == "'${REQUIRED_AUTHOR_ASSOCIATION[0]}'", …
```
> Add `COLLABORATOR` to the `REQUIRED_AUTHOR_ASSOCIATION`

- projects/kserve/testing/config.yaml
- projects/kserve/testing/models/cpt/mistral-7b-instruct-v02.yaml
This should add mistral-7b-instruct-v0.2 to topsail based on my understanding of the configuration in Topsail but I fully expect to need multiple iterations to get the PR in a proper shape. I do not know how to run topsail to test the changes I'm proposing. How do I test running topsail against my branch and the model I'm trying to add?
I did manually deploy the model following the recommended steps and manually ran the validate_model steps to confirm the model could respond to a standard request.
> add mistral-7b-instruct-v02 to tested models

- projects/cluster/roles/cluster_deploy_minio_s3_server/files/deploy_minio.yaml
The previous URL that the `deploy_minio` role was getting RSYNC from looks to have been moved: http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/rsync-3.1.3-19.el8.x86_64.rpm
This is causing the deployed pods to crash. This PR updates the the package to the RPM here:
https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/rsync-3.2.3-20.el9.x86_64.rpm
> [cluster] update rsync url for minio

- projects/cluster/roles/cluster_wait_fully_awake/tasks/main.yml
… if an error was logged on stderr
Example of a [test](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/407/pull-ci-openshift-psap-topsail-main-rhoai-light/1811636193146703872/artifacts/light/prepare/artifacts/002__sutest_rhods__deploy_ods/_ansible.log) that passed when it shouldn't have:
```
2024-07-12 06:13:08,742 p=151 u=psap-ci-runner n=ansible | 
2024-07-12 06:13:08,743 p=151 u=psap-ci-runner n=ansible | <stdout> v1beta1.metrics.k8s.io
2024-07-12 06:13:08,743 p=151 u=psap-ci-runner n=ansible | ==> failed attempt #9/50
2024-07-12 06:13:08,743 p=151 u=psap-ci-runner n=ansible | 
2024-07-12 06:13:39,221 p=151 u=psap-ci-runner n=ansible | 
2024-07-12 06:13:39,221 p=151 u=psap-ci-runner n=ansible | <command>
set -o pipefail; …
```
> [cluster] roles: cluster_wait_fully_awake: tasks/main: do not succeed if an error was logged on stderr

- projects/kserve/testing/test_e2e.py
It looks like the same line has been declared twice with just few lines apart in the global space. So, this is an attempt to remove the duplicate one.
> projects/kserve: removed multiple declarations of the same line

- projects/kserve/testing/test.py
- projects/kserve/testing/test_e2e.py
A call to `visualize.prepare_matbench()` installs python package dependencies from a requirements file that is available in the `"matrix-benchmarking"` repository. This function invocation has been making noise in my local testing by failing to resolve the dependencies due to dependencies conflicts and blocking the execution of remaining steps, such as llm-load-test in "kserve-user-test-driver" container.
This is an attempt to remove the function calls to `visualize.prepare_matbench()` from project/kserve testing as the dependencies are already satisfied in the topsail image. But only thing to remember is that, this results `caikit-nlp-client` in using a higher(or latest) version of "requests" library than desired. 
1. Create a python virtual enviroment
python3 -m venv venv
2. Install …
> Drop `prepare_matbench` function calls from `test_e2e.py`, `test.py` in kserve project

- projects/kserve/testing/config.yaml
OpenShift AI 2.13.0 RC1 is available for Regression Testing.
> Prepare for OpenShift AI `2.13.0 RC1` regression testing

- .github/workflows/build_docs.yml
The `Build docs` action was failing because `actions/upload-artifact@v1` is deprecated, so I updated it to the latest v4. 
Source: [Deprecation notice: v1 and v2 of the artifact actions](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/)
> Update actions/upload-artifact to v4.

- projects/fine_tuning/roles/fine_tuning_run_fine_tuning_job/files/entrypoint/entrypoint.sh
The script `study_dataset.py` sometimes takes up to 5 mins. In order to speed up the process, simple caching was introduced to cache the results of the study script.
> [fine-tuning] Add caching in the entrypoint script.

- projects/fine_tuning/testing/test_finetuning.py
- projects/rhods/library/prepare_rhoai.py
One of the things to precheck before launching a fine-tuning job is to make sure RHOAI is installed in the cluster. This guard does that and exit in case it is not installed.
> Add RHOAI guard for fine-tuning

- testing/run
With the call, the run was failing with this error:
```
stty: 'standard input': Inappropriate ioctl for device
```
> testing: run: remove the column length setting on the perflab

- projects/pipelines/testing/config.yaml
- projects/pipelines/visualizations/rhods-pipelines/store/lts_parser.py
Explicitly handle when there is incomplete Run duration or Run latency data provided.
> [pipelines] Fix panic in KPI parsing

- projects/fine_tuning/testing/test.py
Before this PR, the `metal_profiles` field was used to apply cluster-specific CI presets when a given bare-metal cluster was detected (by searching a known node name in the cluster nodes). This worked only for BareMetal cluster infrastructures (and no defined infrastructure).
Running in a bare-metal cluster without a cluster-profile would raise an exception, so that the cluster name/type is always set via the custom profile. The reason for that is that the cluster type is a critical value to include in the test KPIs.
With this PR, the `metal_profiles` are always looked up and applied (if found). But the exception is still raised only if no cluster profile is found in a baremetal cluster.
> [fine_tuning] testing: test: apply the cluster-profiles even outside of the pure bare-metal clusters

- projects/core/library/ansible_toolbox.py
> [core] library: ansible_toolbox: fix the _python.gen.cmd file when printing flags with quotes

- docs/toolbox.generated/index.rst
- projects/storage/toolbox/storage.py
- projects/storage/toolbox/storage_download_to_image/defaults/main/config.yml
- projects/storage/toolbox/storage_download_to_image/files/entrypoint.sh
- projects/storage/toolbox/storage_download_to_image/meta/main.yml
- projects/storage/toolbox/storage_download_to_image/tasks/main.yml
- projects/storage/toolbox/storage_download_to_image/templates/pod.yml.j2
- projects/storage/toolbox/storage_download_to_image/vars/main/resources.yml
I've got this working locally but need to make sure it works in the CI
> [modelcars] add role to build image

- build/Dockerfile
While running the topsail launcher locally in the podman https://github.com/openshift-psap/topsail/tree/main/launcher - found that python9 is not needed so removing it build the TOPSAIL image
> [Dockerfile] Launcher remove python9 dependency

- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/files/entrypoint/run_fms.sh
As per [this PR](https://github.com/foundation-model-stack/fms-hf-tuning/commit/0888ce2b39946c9c8b1a93f0a086156bb8bc016b), the `launch_training.py` script was removed and all trainings are launched by calling `sft_trainer` module directly.
> Clean fms-hf-tuning entrypoint

- projects/jump_ci/toolbox/jump_ci_prepare_topsail/tasks/main.yml
Prevents [this error](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift-psap_topsail/650/pull-ci-openshift-psap-topsail-main-jump-ci/1882518904341794816/artifacts/ci/002-prepare-jump-ci/artifacts/001__jump_ci__prepare_topsail/_ansible.log):
```
<stderr> error: Your local changes to the following files would be overwritten by checkout:
<stderr> 	matrix_benchmarking/analyze/report.py
<stderr> Please commit your changes or stash them before you switch branches.
<stderr> Aborting
<stderr> fatal: Unable to checkout '1dfbdc2dd561df5d69d903680ec5b25050c17809' in submodule path 'projects/matrix_benchmarking/subproject'
<stderr> Error: error building at STEP "RUN git submodule --quiet update --init --recursive": error while running runtime: exit …
```
> [jump_ci] toolbox: jump_ci_prepare_topsail: tasks/main: force update the submodules

- docs/extending/orchestration.rst
- projects/local_ci/library/prepare_user_pods.py
- projects/local_ci/toolbox/local_ci_run/templates/pod.yaml.j2
* The variable `HOMELAB_CI` has been replaced with `TOPSAIL_LOCAL_CI`, allowing TOPSAIL to build base images from the PR instead of `topsail:main`.
> Updated the naming convention, replacing HOMELAB_CI with TOPSAIL_LOCAL_CI

- docs/toolbox.generated/Fine_Tuning.run_fine_tuning_job.rst
- projects/fine_tuning/toolbox/fine_tuning.py
- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/defaults/main/config.yml
- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/files/entrypoint/entrypoint.sh
- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/files/entrypoint/run_fms.sh
- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/tasks/main.yml
- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/templates/fine_tuning_job.yaml.j2
- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/templates/retrieval_pod.yaml.j2
- projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/vars/main/resources.yml
In order to retrieve files from the fine-tuning Pod execution, we enable by default the `--retrieve-files` flag. 
* The mounting point of the files to be exported as artifacts is [/mnt/storage/output](https://github.com/openshift-psap/topsail/pull/652/files#diff-df818cb4be74252e4ce9361ac6e4c732d2c49b2836aab5266295535037c150d0R9) by default.
* The logic for copying the files is written in the [entrypoint](https://github.com/openshift-psap/topsail/pull/652/files#diff-bc78a290b2c47f14480b1c35286b55175d720ce800bea808f18dc6a2cab835abR27).
> [fine_tuning]: Add fine-tuning pod file retrieval

- projects/fine_tuning/testing/config.yaml
This PR also includes a change to use RHOAI 2.17.0 RC2.
> [fine_tuning] Update max_seq_length for QLoRA validation

- projects/fine_tuning/visualizations/fine_tuning/store/__init__.py
To avoid visualization issues, drop `hyper_parameters.skip_if` from the settings list.
> Drop hyper_parameters.skip_if from settings

- .gitignore
- launcher/topsail_enter
- projects/core/library/ansible_toolbox.py
- projects/core/library/config.py
- projects/core/library/run.py
- projects/matrix_benchmarking/library/visualize.py
- projects/matrix_benchmarking/visualizations/helpers/store/__init__.py
- variable_overrides.yaml.sample
* `[launcher] topsail_enter: add a 'here' flag to avoid moving to topsail directory`
*   simple helper flag that makes `topsail_enter here` behaves as `topsail_enter`
* `[matrix_benchmarking] library: visualize: show the artifact directory`
* its convenient when running locally to see the directory where the error file is generated
* `[matrix_benchmarking] visualizations: helpers: store/__init__: improve the error fallback`
* old typo in the code that wasn't triggered before ...
* `[core] library: config: ease the configuration of TOPSAIL for local execution`
* first step for the rewriting of `./run_toolbox.py configure enter fine_tuning '--presets=["ilab_l40s_scale"]'` is a more convenient way (without relying on env variables ...)
* `[core] library: config: remove the code to dump the …
> [TOPSAIL] Small convenience improvements

- projects/core/library/ansible_toolbox.py
```
* [core] library: ansible_toolbox: allow receiving TOPSAIL_ANSIBLE_PLAYBOOK_EXTRA_ENV yaml file to give declare extra env values in the Ansible playbook
* [core] library: ansible_toolbox: use the correct var in the error handler
* [core] library: ansible_toolbox: minor reindent  
```
> [TOPSAIL] Minor improvements

- docs/toolbox.generated/Llm_Load_Test.run.rst
- projects/llm_load_test/toolbox/llm_load_test.py
- projects/llm_load_test/toolbox/llm_load_test_run/defaults/main/config.yml
- projects/llm_load_test/toolbox/llm_load_test_run/tasks/main.yml
- projects/llm_load_test/toolbox/llm_load_test_run/templates/llm-load-test-config.yaml.j2
Relocating the llm-load-test visualization to a more logical place.
(I want to use the `llm-load-test` project outside of the `kserve` project)
/cc @mcharanrm
> [llm_load_test] Make more generic for testing on other platforms

- projects/core/library/config.py
* `ibm-granite/granite-3.0-8b-instruct@hf` was incorrectly detected as a config dereference
* key `ci_presets.light["tests.fine_tuning.test_settings.model_name"]` cannot be updated by `config.set_config` (because of the dots in the last field). Now writing a log message to tell we were trying to do this.
> [core] library: config: resolve_references: make more reliable

- docs/requirements.txt
```
The conflict is caused by:
sphinx-rtd-theme 1.3.0 depends on docutils<0.19
myst-parser 4.0.1 depends on docutils<0.22 and >=0.19
```
> docs: requirements: fix dependencies

- projects/kserve/testing/config.yaml
The email didn’t include a tag, so I used a custom tag with the valid SHA digest provided. Clients will always pull the image using the SHA digest. If a valid tag is given but the digest is invalid, clients won’t be able to download the image. 
The SHA digest is only considered when both a tag and digest are provided.
> Kserve: RHOAI 2.18.0 RC performance gating

- projects/mac_ai/testing/config.yaml
- projects/mac_ai/testing/images/llama_cpp.containerfile
- projects/mac_ai/testing/prepare_llama_cpp.py
see https://github.com/ggml-org/llama.cpp/pull/14501
> [mac_ai] testing: remove the `kompute` flavor
