openshift-psap/topsail

testing/load-aware/config.yaml
Ticket has been closed and shouldn't be used
=> testing: load-aware: config: remove Ticket #115

testing/codeflare/config.yaml
=> testing: codeflare: config: disable TicketID 160

testing/notebooks/config.yaml
=> testing: notebooks: config: disable TickedId 85 and 86

roles/cluster/cluster_deploy_kubemark_nodes/tasks/main.yml
otherwise they get all overwritten
=> cluster_deploy_kubemark_nodes: save the Kubemark pods in differente files

roles/cluster/cluster_update_pods_per_node/defaults/main/config.yml, roles/cluster/cluster_update_pods_per_node/meta/main.yml, roles/cluster/cluster_update_pods_per_node/tasks/main.yml, roles/cluster/cluster_update_pods_per_node/template/kubeletconfig.yaml.j2, roles/cluster/cluster_update_pods_per_node/vars/main/resources.yml, roles/gpu_operator/gpu_operator_extend_metrics/tasks/main.yml, roles/local_ci/local_ci_run_multi/tasks/main.yml, roles/watsonx_serving/watsonx_serving_deploy_model/tasks/main.yml, testing/utils/openshift_clusters/ocp_cluster.sh, testing/watsonx-serving/command_args.yml.j2, testing/watsonx-serving/config.yaml, testing/watsonx-serving/models/flan-t5-small-gpu-light.yaml, testing/watsonx-serving/prepare_watsonx_serving.py, testing/watsonx-serving/test_scale.py, toolbox/cluster.py
=> Serving: update for running at scale

topsail/_common.py
This commit makes sure the collections paths array have only strings.
=> Make sure we store strings in collection paths

projects/kserve/testing/config.yaml, projects/kserve/testing/models/bloom-560m.yaml, projects/kserve/testing/models/flan-t5-large-gpu.yaml, projects/kserve/testing/models/flan-t5-small-gpu.yaml, projects/kserve/testing/models/gpt-neox-20b.yaml, projects/kserve/testing/models/mpt-7b-instruct2.yaml, projects/kserve/testing/models/template.yaml, projects/kserve/testing/test_e2e.py, projects/kserve/visualizations/kserve-llm/store/lts_parser.py, topsail/testing/matbenchmark.py
Start integrating MatrixBenchmarking/benchmark testing in the `kserve` project
=> [kserve] Test matbenchmarking 

projects/notebooks/visualizations/rhods-notebooks-performance/models/lts.py, projects/notebooks/visualizations/rhods-notebooks-performance/store/lts_parser.py, projects/notebooks/visualizations/rhods-notebooks-performance/store/parsers.py
Reverts openshift-psap/topsail#182
=> Revert "[notebooks] visualizations: rhods-notebooks-performance: parse the test identifiers"

projects/kserve/roles/kserve_capture_state/tasks/main.yml, projects/kserve/testing/config.yaml, projects/kserve/testing/test.py, projects/kserve/testing/test_e2e.py, projects/kserve/visualizations/kserve-llm/models/lts.py, projects/kserve/visualizations/kserve-llm/store/__init__.py, projects/kserve/visualizations/kserve-llm/store/lts_parser.py, projects/kserve/visualizations/kserve-llm/store/parsers.py, projects/local-ci/roles/local_ci_run_multi/templates/job.yaml.j2, testing/run, testing/utils/openshift_ci/pr_args.sh, topsail/testing/config.py
/var matbench.download.mode=important
=> [kserve] Add KServe Testing Labels

projects/kserve/testing/config.yaml
=> [kserve] Remove deprecated models

projects/kserve/testing/config.yaml
intlab upload failure: https://ci.app-svc-perf.corp.redhat.com/job/ExternalTeams/job/RHODS/job/topsail/160/artifact/run/f23-h33-000-6018r.rdu2.scalelab.redhat.com/002_test_ci/003__plots/000__projects.kserve.visualizations.kserve-llm_plots/5_matbench_upload_lts.log/*view*/
=> [kserve] Update the configuration

projects/kserve/testing/models/base-standalone-tgis.yaml, projects/kserve/testing/models/flan-t5-small-hf.yaml, projects/kserve/testing/models/watsonx-codellama-34b-instruct-hf.yaml, projects/kserve/testing/models/watsonx-flan-t5-xl.yaml, projects/kserve/testing/models/watsonx-flan-t5-xxl.yaml, projects/kserve/testing/models/watsonx-japanese-llama-2-7b-instruct.yaml, projects/kserve/testing/models/watsonx-llama-2-13b-chat-hf.yaml, projects/kserve/testing/models/watsonx-llama-2-70b-chat-hf.yaml, projects/kserve/testing/models/watsonx-mpt-7b-instruct2.yaml
rebased on top of #246 and main
=> Add MAX_SEQUENCE_LENGTH and MAX_NEW_TOKENS environments 

projects/repo/toolbox/repo.py
=> [repo] toolbox: repo: do not swallow 'validate_no_wip' error

projects/kserve/testing/config.yaml
=> [kserve] testing: config: disable LTS upload

projects/core/library/config.py, testing/run
This PR is mainly intended to get me onto the list of contributors so I can run tests from PR comments ;)
=> Fix minor log typos

projects/fine_tuning/visualizations/fine_tuning/store/parsers.py
=> [fine_tuning] visualizations: fine_tuning: store/parsers: do not crash if the dataset stats couldn't be computed

projects/fine_tuning/visualizations/fine_tuning/store/lts_parser.py, projects/fine_tuning/visualizations/fine_tuning/store/parsers.py
=> [fine_tuning] visualizations: fine_tuning: do not crash if the Pod execution didn't complete

projects/fine_tuning/testing/config.yaml, projects/fine_tuning/visualizations/fine_tuning_prom/plotting/prom_summary.py, projects/fine_tuning/visualizations/fine_tuning_prom/store/__init__.py
=> [fine-tuning] move meta-llama/Llama-2-13b-chat-hf ibm-granite/granite-20b-code-instruct to the 40GB DGX

projects/cluster/roles/cluster_deploy_minio_s3_server/files/deploy_minio.yaml, projects/cluster/roles/cluster_wait_fully_awake/tasks/main.yml, projects/local_ci/roles/local_ci_run_multi/tasks/main.yml, projects/local_ci/roles/local_ci_run_multi/templates/job.yaml.j2, projects/notebooks/roles/notebooks_dashboard_scale_test/files/entrypoint.sh, projects/notebooks/roles/notebooks_dashboard_scale_test/tasks/main.yml, projects/notebooks/roles/notebooks_dashboard_scale_test/templates/ods-ci_job.yaml, projects/notebooks/roles/notebooks_locust_scale_test/templates/locust_job.yaml, projects/notebooks/roles/notebooks_ods_ci_scale_test/files/entrypoint.sh, projects/notebooks/roles/notebooks_ods_ci_scale_test/files/s3-artifacts-exporter.sh, projects/notebooks/roles/notebooks_ods_ci_scale_test/tasks/artifacts_driver.yml, projects/notebooks/roles/notebooks_ods_ci_scale_test/tasks/main.yml, projects/notebooks/roles/notebooks_ods_ci_scale_test/templates/ods-ci_job.yaml
The `minio` changes have been originally introduced by Supraja Manda as part of https://github.com/openshift-psap/topsail/pull/407.
Merge them independently of her PR to ease the integration testing.
=> Add an SSL layer to the cluster Minio endpoint

projects/cluster/roles/cluster_deploy_operator/tasks/main.yml
=> [cluster] roles: cluster_deploy_operator: tasks/main: do not fail if our operatorgroup exists

projects/kserve/roles/kserve_deploy_model/files/patch/patch-servingruntime.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/base/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/granite-20b-code-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/granite-20b-code-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/granite-3b-code-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/granite-3b-code-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/granite-8b-code-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/granite-8b-code-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/llama-3-70b-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/llama-3-70b-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/llama-3-8b-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/standalone-tgis/models/llama-3-8b-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/base/inferenceservice.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/base/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/base/servingruntime.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/granite-20b-code-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/granite-20b-code-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/granite-3b-code-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/granite-3b-code-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/granite-8b-code-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/granite-8b-code-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/llama-3-70b-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/llama-3-70b-instruct/patch.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/llama-3-8b-instruct/kustomization.yaml, projects/kserve/roles/kserve_deploy_model/files/vllm/models/llama-3-8b-instruct/patch.yaml, projects/kserve/testing/config.yaml, projects/kserve/testing/test_e2e.py
Update set of models and a few other fixes
=> [kserve] Update set of models

projects/fine_tuning/visualizations/ibm_comparison/data/plots.yaml, projects/fine_tuning/visualizations/ibm_comparison/models/kpi.py, projects/fine_tuning/visualizations/ibm_comparison/models/lts.py, projects/fine_tuning/visualizations/ibm_comparison/plotting/__init__.py, projects/fine_tuning/visualizations/ibm_comparison/plotting/comparison.py, projects/fine_tuning/visualizations/ibm_comparison/plotting/comparison_report.py, projects/fine_tuning/visualizations/ibm_comparison/plotting/report.py, projects/fine_tuning/visualizations/ibm_comparison/requirements.txt, projects/fine_tuning/visualizations/ibm_comparison/store/__init__.py, projects/fine_tuning/visualizations/ibm_comparison/store/lts_parser.py, projects/fine_tuning/visualizations/ibm_comparison/store/parsers.py
=> [fine_tuning] visualizations: ibm_comparison: new visualization module for comparing RH and IBM results

docs/contrib.rst, docs/contributing.rst, docs/index.rst
This commit includes new documentation
for newcomers.
=> Documentation refactor

projects/fine_tuning/roles/fine_tuning_run_fine_tuning_job/files/entrypoint/entrypoint.sh
=> [fine_tuning] roles: fine_tuning_run_fine_tuning_job: files/entrypoint/entrypoint: fix undefined variable

projects/pipelines/visualizations/rhods-pipelines/models/kpi.py
=> [pipelines] visualizations: rhods-pipelines: models/kpi: use the LowerBetter annotation

projects/cluster/roles/cluster_download_to_pvc/files/entrypoint.sh
=> [cluster] roles: cluster_download_to_pvc: files/entrypoint: correctly store the sha256sum of the downloaded files

projects/repo/toolbox/notifications/github/api.py, projects/repo/toolbox/notifications/send.py, projects/repo/toolbox/notifications/slack/api.py, requirements.txt
Add Slack integration for Topsail updates.
=> [TOPSAIL Bot] Enable TOPSAIL to send Slack App messages

projects/repo/toolbox/notifications/send.py, projects/repo/toolbox/notifications/slack/api.py
=> [repo] toolbox: notifications: send: enable slack notification with LocalCI

projects/fine_tuning/visualizations/fine_tuning/plotting/sfttrainer.py
=> [fine_tuning] visualizations: fine_tuning: plotting/sfttrainer: remove code added by mistake

projects/fine_tuning/testing/config.yaml, projects/fine_tuning/testing/prepare_finetuning.py, projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/templates/fine_tuning_job.yaml.j2, projects/fine_tuning/visualizations/fine_tuning/plotting/sfttrainer.py, projects/matrix_benchmarking/library/visualize.py, projects/storage/toolbox/storage_download_to_pvc/files/entrypoint.sh, projects/storage/toolbox/storage_download_to_pvc/tasks/main.yml
Most of this PR is based on @albertoperdomo2 's early+ongoing work in https://github.com/openshift-psap/topsail/pull/519
=> [Fine-tuning] Test QLoRA preset

projects/storage/toolbox/storage_download_to_pvc/tasks/main.yml
=> [storage] toolbox: storage_download_to_pvc: tasks/main: correctly detect the pod completion

projects/fine_tuning/visualizations/fine_tuning_prom/plotting/prom_summary.py
=> [fine_tuning] visualizations: fine_tuning_prom: plotting/prom_summary: finish fixing the removal of the expe setting

projects/core/library/config.py, projects/fine_tuning/testing/config.yaml, projects/kserve/testing/config.yaml, projects/matrix_benchmarking/library/visualize.py, projects/pipelines/testing/config.yaml, testing/run
=> [matrix_benchmarking] library: visualize: improve the replot configuration

.github/steps/prepare_minimal_ubuntu_image/action.yml, .github/workflows/build_docs.yml
```
no such option: --break-system-packages
Error: Process completed with exit code 2.
```
not sure why I had to insert it yesterday :/
https://github.com/openshift-psap/topsail/pull/566
=> [Github Actions] Remove `--break-system-packages` flag

projects/core/library/config.py, projects/fine_tuning/visualizations/fine_tuning/plotting/sfttrainer.py, projects/fine_tuning/visualizations/fine_tuning_prom/plotting/prom_summary.py, projects/fine_tuning/visualizations/fine_tuning_prom/store/__init__.py, projects/kserve/visualizations/kserve-prom/store/__init__.py, projects/local_ci/toolbox/local_ci_run/templates/pod.yaml.j2, projects/local_ci/toolbox/local_ci_run_multi/templates/job.yaml.j2, projects/repo/toolbox/notifications/send.py, testing/rhoai.py, testing/run, testing/utils/configure_overrides.sh, testing/utils/openshift_ci/pr_args.sh
See the related (internal) MiddlewareCI update in this PR: https://gitlab.cee.redhat.com/middlewareperformance/performance-lab-scripts/-/merge_requests/154
=> [TOPSAIL] Use YAML to pass the variable overrides

projects/llm_load_test/toolbox/llm_load_test_run/templates/llm-load-test-config.yaml.j2
Bump llm-load-test to include the openai_plugin refactor and dropping of warmup support.
=> [llm-load-test] subproject: bump llm-load-test

projects/fine_tuning/testing/config.yaml, projects/fine_tuning/testing/test_finetuning.py, projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/files/entrypoint/run_ilab.sh, projects/fine_tuning/toolbox/fine_tuning_run_fine_tuning_job/tasks/main.yml, projects/fine_tuning/visualizations/fine_tuning/plotting/error_report.py, projects/fine_tuning/visualizations/fine_tuning/plotting/ilab_training.py, projects/matrix_benchmarking/visualizations/helpers/store/prom.py
=> [fine_tuning] testing: make it easier to configure the secondary NIC count

projects/fine_tuning/testing/config.yaml, projects/fine_tuning/testing/test.py
Add a new metal cluster and fix a typo.
=> [fine_tuning]: Enable Prow

projects/jump_ci/toolbox/jump_ci_prepare_topsail/tasks/main.yml
=> [jump_ci] toolbox: jump_ci_prepare_topsail: tasks/main: fix don't prune `preserve=true` images

projects/matrix_benchmarking/library/visualize.py
=> [matrix_benchmarking] library: visualize: fix an incorrectly named variable

projects/fine_tuning/visualizations/fine_tuning/store/parsers.py
=> [fine_tuning] visualizations: fine_tuning: store/parsers: make the Ray parser more reliable

projects/kserve/toolbox/kserve_capture_state/tasks/main.yml, projects/pipelines/toolbox/pipelines_capture_state/tasks/main.yml
Fix the use of Ansible restricted words in both KServe and Pipelines project.
=> Fix use of Ansible's restricted words

projects/server/toolbox/server_deploy_minio_s3_server/files/deploy_minio.yaml, requirements.txt
=> [server] toolbox: server_deploy_minio_s3_server: files/deploy_minio: update Minio image version

projects/fine_tuning/testing/config.yaml, projects/fine_tuning/testing/prepare_finetuning.py, projects/rhods/toolbox/rhods_undeploy_ods/tasks/main.yml
Fork of https://github.com/openshift-psap/topsail/pull/666 to run Jump CI
=> Rhoai 2.17 rc

build/Dockerfile
Make sure Topsail container can run everything in MacOS.
=> Enable Topsail container in MacOS

ansible-config/ansible.cfg, projects/core/library/ansible_toolbox.py, projects/core/library/run.py, projects/jump_ci/testing/config.yaml, projects/jump_ci/testing/test.py, projects/jump_ci/testing/tunnelling.py, projects/jump_ci/toolbox/jump_ci_prepare_step/tasks/main.yml, projects/jump_ci/toolbox/jump_ci_prepare_step/templates/entrypoint.sh.j2, projects/jump_ci/toolbox/jump_ci_prepare_topsail/tasks/main.yml, testing/run
This PR goes along with https://github.com/openshift/release/pull/62245
=> [TOPSAIL] Improve the Jump-CI and other details

projects/mac_ai/visualizations/llm_load_test/plotting/throughput.py
=> [mac_ai] visualizations: llm_load_test: plotting/throughput: improve the multi-model plot

projects/jump_ci/testing/prepare_jump_ci.py
fix of https://github.com/openshift-psap/topsail/pull/778
=> [jump_ci] testing: prepare_jump_ci: correctly create the dict

projects/matrix_benchmarking/visualizations/helpers/store/parsers.py
solves this failure: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-psap-topsail-main-mac_ai-jump-ci-cpt/1941829763488288768/artifacts/jump-ci-cpt/005-test/artifacts/test-artifacts/004__plots/0_matbench_parse.log
=> [matrix_benchmarking] visualizations: helpers: store/parsers: rewrite to work correctly with periodic jobs
